### ISSUE TITLE
Richer YAML highlighting

### ISSUE THREAD

**Issue by ahmetb** [alecthomas/chroma#118]
I am using Hugo (http://gohugo.io) which uses Chroma to highlight some YAML content. 

I ended up with this even though I am using the styles:

![image](https://user-images.githubusercontent.com/159209/36228977-9f1e4306-118a-11e8-96cc-387001cbc5dc.png)

The VSCode yaml highlighter gives richer annotations for fields and values:

![image](https://user-images.githubusercontent.com/159209/36228994-a9e6d97e-118a-11e8-99e5-07a74c9b5092.png)

Can chroma do better here?

**Comment by alecthomas** [comment]
Chroma should highlight values reasonably well. The only difference I see in your examples is colour and a spurious "1.0". Chroma is aware of comments, preprocessor directives, strings, numbers, keywords, block quotes, etc.

Where it is lacking is keys, because that would essentially require a full YAML parser and YAML is extremely annoying to parse. The [Pygments lexer](https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/data.py?at=default&fileviewer=file-view-default#data.py-22) is 400 lines long with ~50 lines of custom logic to deal with its insanity.

For example, this is a valid key:

```yaml
foo: bar
? - Manchester United
  - Real Madrid
: [ 2001-01-01, 2002-02-02 ]
```

As is this:

```yaml
foo: bar
? !!python/tuple [5, 7]
: Fifty Seven
```

In fact, you can see that GitHub's highlighter does not highlight these correctly.

That said, Chroma does reasonably well on [this sample](https://learnxinyminutes.com/docs/yaml/).

**Comment by ahmetb** [comment]
Could there be a middle ground? Like highlighting the keys differently, if they're really obvious (like GitHub or vscode does)?

**Comment by moorereason** [comment]
I noticed [in the Hugo docs](https://gohugo.io/content-management/menus/#add-non-content-entries-to-a-menu) that chroma is thrown off by the ending `>` in the following content:

```yaml
pre: <i class='fa fa-heart'></i>
url: /about/
```

@alecthomas, I agree that YAML sucks (and we should probably quote our YAML strings), but is this more of an upstream issue with Pygments or are you going to maintain a forked YAML lexer inside chroma?

**Comment by ahmetb** [comment]
1.5 years later, I came to find the very issue I was about to open, already opened by myself.

It seems like the YAML lexer is still not doing great. :(
This is especially sad for the Hugo project which is now widely used by the ecosystem projects around the Kubernetes community  which is YAML-driven.

For a yaml like:

```yaml
key1: value1
key2: "value2"
```

As you can see GitHub can distinguish keys from values.

However `chroma --lexer=yaml --formatter=html kv.yaml` doesn't even put a class around the `key1`, or `value1` or `key2` above (it only recognizes `"value2"` literal as something worth highlighting:

```
<pre class="chroma">key1<span class="p">:</span><span class="w"> </span>value1<span class="w">
</span><span class="w"></span>key2<span class="p">:</span><span class="w"> </span><span class="s2">&#34;value2&#34;</span><span class="w">
</span></pre>
```

Can we please at least get some basic colors for YAML keys? (See the screenshot I posted in the first comment.)
