### ISSUE TITLE
Shell code block that ends with comment, incorrectly highlighted

### ISSUE THREAD

**Issue by will-stone** [alecthomas/chroma#168]
Hi, thanks for Chroma. I really like using it with Hugo.

I've noticed if a `sh` block ends in a comment, it doesn't receive the comment colour. Is this normal?

<img width="530" alt="image" src="https://user-images.githubusercontent.com/654103/45452476-f6d14800-b6d5-11e8-9a1d-f3b9f30525c9.png">

<img width="499" alt="image" src="https://user-images.githubusercontent.com/654103/45452531-22ecc900-b6d6-11e8-8794-54d8a2367ced.png">

**Comment by Jos512** [comment]
Thanks for the comment and detailed information. I was able to replicate this error and proposed a fix for it (#169). If Alec accepts that code change, the fix will be in Chroma.

It might take a little while before you see the fix in Hugo appear too. That's because first Chroma needs to have a new release. Then Hugo needs a new release so it can pull in the updated Chroma. :slightly_smiling_face:
