### ISSUE TITLE
Pipe symbol in yaml corrupts syntax highlighting.

### ISSUE THREAD

**Issue by JorritSalverda** [alecthomas/chroma#194]
With the following `yaml` in my markdown the highlighting suddenly changes colour at the pipe symbol. It does this regardless of the backticks.

```yaml
commands:
- go test `go list ./... | grep -v /vendor/`
```

See https://estafette.io/usage/examples/#golang for the incorrect result.

Is this correct behaviour or a bug? Any way to prevent this from happening?

**Comment by Jos512** [comment]
This issue is fixed in #194 I believe.

If you use Chroma directly from GitHub it shouldn't happen anymore, Jorrit. If you use another tool that uses Chroma (like Hugo) then you'll need to wait until there's a new release for that software before you see the fix.

Thanks for the issue report, by the way. :slightly_smiling_face:

**Comment by alecthomas** [comment]
Thanks @Jos512 👍

**Comment by JorritSalverda** [comment]
Thanks for fixing this. Any eta on the next release? I indeed use Hugo, for which the devs probably only want to update to 'official' releases instead of master :)

**Comment by JorritSalverda** [comment]
@alecthomas when do you think you'll create a new release so hugo can incorporate the fix for this issue? Thx

**Comment by alecthomas** [comment]
Tagged 0.6.1 👍
