### ISSUE TITLE
PHP is not recognized without leading, opening PHP tag

### ISSUE THREAD

**Issue by www-flomei-de** [alecthomas/chroma#210]
While using Chroma in the [Hugo static site generator,](https://gohugo.io) I found that PHP code is not recognized by Chroma, without an opening PHP tag.

This has already been mentioned in #80 but that issue was closed.

As of now, this though still seems to be an issue/problem, as [I found out here,](https://discourse.gohugo.io/t/no-classes-added-to-syntax-highlighting/16004/11) where my code wasn't correctly recognized/highlighted without that leading PHP tag.

How can I help to get this fixed for future versions?

**Comment by alecthomas** [comment]
There’s a test that works, as part of that commit. Are you sure you’re using the Correct lexer?

**Comment by alecthomas** [comment]
Ah I see this is slightly different. Is it even possible to execute PHP code without the tags? Does pygments work with this format?

**Comment by moorereason** [comment]
AFAIK:
* The PHP interpreter requires a start tag (`<?php` or `<?`).
* Pygments will not highlight PHP without a start tag.

I recommended that @www-flomei-de create an issue here after he raised the issue in the Hugo forums. I'm assuming it's rather boring to have to add start tags for code snippets in an article.

Just for comparison, the Github markdown render [highlights PHP codeblocks without start tags](https://gist.github.com/moorereason/80fdbd8d47b0048c5a592f9a19db4a83) (although you can't do that with a PHP file, and you can apparently just mix HTML in with it at random).

Chroma is already making Hugo more awesome, @alecthomas, so thanks for your consideration here.

**Comment by alecthomas** [comment]
It seems there is a conflict between "correctness" and convenience here. The Github renderer is convenient, but will highlight PHP tokens even when it shouldn't, as in your first example in that gist. I don't love that and off the top of my head it seems like it would be quite difficult to implement due to the way Chroma (and Pygments) lexers are implemented.

Pygments "solves" this with a [startinline](http://pygments.org/docs/lexers/#lexers-for-php-and-related-languages) option which Chroma could also do (as discussed in #80), but there's no way to pass that through Markdown.

Another option is to create a separate lexer eg. `php-inline`, but people would need to know to use this and it's not very obvious.

I'm open to ideas, but I don't see a good solution here.

**Comment by moorereason** [comment]
The `startinline` option would work.

Cc: @bep

**Comment by bep** [comment]
I vote for a “will not fix”

**Comment by alecthomas** [comment]
Agreed @bep.

**Comment by Kovah** [comment]
> I vote for a “will not fix”

Does that mean that this feature is already possible with the `startinline` option, or that Chrome will not implement this feature.

**Comment by alecthomas** [comment]
The latter.

**Comment by Rarst** [comment]
I'd like to chime in that it's not a purpose of syntax highlighter to compile and run valid PHP code. The purpose is to highlight the code examples in content.

It is a perfectly normal _content_ practice to omit opening PHP tags in code snippets. They accomplish nothing in that context.

I was looking forward to ditch client-side highlight when moving to Hugo, but this makes it simply not a practical option for the PHP. 😞

**Comment by bitwombat** [comment]
I've never seen the opening PHP tag in code snippets in articles. Makes sense since snippets are usually from the somewhere in the middle of a complete body of code. Putting the opening PHP tag in all my snippets would change the meaning of the snippet. It would be saying "This code goes at the top of the file". The opening tag is basically an anchor.

The behavior as is means chroma does not highlight PHP code snippets.

**Comment by Radiergummi** [comment]
@alecthomas I would like to urge you to reconsider this decision, as the current behavior is highly unintuitive for anyone that actually uses PHP code snippets. Mixed HTML/PHP is really unusual these days, aside from plain PHP templates; the 95% use case is having PHP code blocks highlight PHP code without the opening tag.  
My suggestion would be to go the other way around this and introduce a new `phtml` lexer for the current behavior, as that is a community convention and it just makes sense.

**Comment by alecthomas** [comment]
It seems like there's consensus that the current approach is not ideal. I'm happy to accept a PR adding a phtml lexer and changing the behaviour of the PHP one.

**Comment by alecthomas** [comment]
Okay, give that a whirl and let me know if there are any issues.
