### ISSUE TITLE
Text not readable with "rrt" style

### ISSUE THREAD

**Issue by mewmew** [alecthomas/chroma#212]
Hi Alec,

I've had great fun these last few days taking Chroma out for a spin!

Wrote a quick script that allows you to select the Chroma style to use. All works fine, except one it seems. The text of `rrt` style is not readable, as it uses black foreground text on black background.

PoC:

https://mewspring.github.io/poc/chroma/rrt/main_c_0001.html

![2019-01-02-212727_1081x486_scrot](https://user-images.githubusercontent.com/1414531/50611403-847bb200-0ed6-11e9-8f83-14de61e6943a.png)

![2019-01-02-212747_1011x478_scrot](https://user-images.githubusercontent.com/1414531/50611406-86de0c00-0ed6-11e9-8403-fb00872b2b17.png)

Cheers,
Robin

**Comment by Jos512** [comment]
I see the problem, thanks for reporting it.

The issue happens because Chroma's [rtt.go](https://github.com/alecthomas/chroma/blob/master/styles/rrt.go) style doesn't recognise everything. If I look at [the Pygments source](https://bitbucket.org/birkenfeld/pygments-main/src/daa5f1ddb461044e2201d1292f6aa77fb20c2026/pygments/styles/rrt.py?at=default&fileviewer=file-view-default) (which Chroma is based on), then Pygments neither highlights that much. [Here's](http://help.farbox.com/pygments.html) a webpage with the output that Pygments makes, and there the rtt style also lacks highlight for various code elements.

With a bit of digging I did find [here](https://github.com/Anomareh/pygments-styles-dump/blob/master/rrt.css) what Pygments uses for rtt. That source is, however, five years old. If it would be more recent, I'd use that source and make a pull request for this issue. But now I'm not sure what the best approach is.

Any thoughts? If that older source is okay, I'd happily send in a pull request.

**Comment by mewmew** [comment]
@Jos512, thanks for diving into this problem!

> Any thoughts? If that older source is okay, I'd happily send in a pull request.

I think @alecthomas would have to decide on the approach best suited.

**Comment by alecthomas** [comment]
I think it just needs a default text colour set in the theme. I'd definitely appreciate a PR @Jos512, thank you.
