### ISSUE TITLE
Julia transpose

### ISSUE THREAD

**Issue by matbesancon** [alecthomas/chroma#253]
Julia uses `A'` to transpose an array, but it seems to be parsed as char opening character in all cases
![image](https://user-images.githubusercontent.com/7623090/57437583-5d493e80-7242-11e9-9644-80294b3c397a.png)

**Comment by ammo0110** [comment]
Same problem exists with Octave matrix transpose

![issue](https://user-images.githubusercontent.com/35888494/57531521-595b1080-7357-11e9-97b4-b59f236f6e54.png)

Should I report a separate bug for this?

**Comment by matbesancon** [comment]
I think the two could live here

**Comment by ammo0110** [comment]
I checked with latest pygments classic to see whether this problem exists there or not. Looks like it has been fixed in pygments.

![Screenshot from 2019-05-11 11-02-47](https://user-images.githubusercontent.com/35888494/57565507-a59c6400-73dc-11e9-9115-b746c8fd9cdc.png)

Let me know if this helps in diagnosing and fixing the bug.

**Comment by alecthomas** [comment]
I think this should be fixed. Give latest master a whirl.

**Comment by matbesancon** [comment]
Indeed fixed in master, thanks a lot

**Comment by alecthomas** [comment]
I've also tagged this as v0.6.4, which fixes a fairly major bug. And when I say "major" I mean it incorrectly highlighted, not exploded, so not really that major :)
