### ISSUE TITLE
Add support for ANSI espaced plain text 

### ISSUE THREAD

**Issue by ssbarnea** [alecthomas/chroma#345]
While `ANSI escaped` text is not a programming language by itself, being able to convert it to JavaScript would enable users to copy/paste terminal output in Markdown documents in order to document output without having to make screenshots.

This feature would be great for creating console output examples.

**Comment by alecthomas** [comment]
i don't understand what role you think Chroma would play here. It highlights text, what does "support for ANSI escaped text" mean exactly?

**Comment by fazalmajid** [comment]
I think he means a lexer to colorize raw terminal console output with embedded ANSI color escape codes, as done by the `console` lexer in Pygments. That would be useful to embed ANSI-colorized terminal output in a Hugo blog without resorting to asciinema or the like.

If you'd be interested in a pull request to implement such a thing, I'd be happy to take a stab at it as that was precisely what I was trying to do today on my Hugo blog.

**Comment by alecthomas** [comment]
I'm not sure how you'd implement something like that in Chroma. It doesn't do any transformation of output, so the ANSI escape sequences would still be present.

**Comment by fazalmajid** [comment]
Yes, I realized after my comment that Pygments does not actually tokenize ANSI color codes and just passes them on unlike what I thought.

I was thinking of perhaps using a new token type for color codes. It wouldn't be a presentational and not a semantic one unlike the others, and styles wouldn't know how to deal with them, but would that be an approach you would be OK with?

**Comment by alecthomas** [comment]
I'm open to ideas, but I don't think this is the right approach. It will mix ANSI colour implementation details in with general purpose tokens.

**Comment by fazalmajid** [comment]
What would you recommend? ANSI codes in the input have no intrinsic semantic meaning and don't map to the styles' existing fields. Should this be done by something like Pygments filters instead? It's formatter-specific, though.

The output of a `console` lexer doesn't have many distinct tokens in it (from what I can see, only GenericOutput), but an ANSI color-coded section may straddle lines so that edge case has to be handled properly (although chroma seems to generate only one GenericOutput token, vs Pygments that generates one per line).
