### ISSUE TITLE
A style that just uses the terminal's 16 colors

### ISSUE THREAD

**Issue by raph-amiard** [alecthomas/chroma#409]
I use terminal with light backgrounds during day and dark during night.

For the moment, I didn't find a way to configure chroma so that it has a set of command line options that works equally well with a dark background terminal and a light background terminal, and also doesn't use strange colors. This feature request might seem a bit basic but, how hard would it be to just have a mode that uses the terminal default 16 colors, so that I have something that actually fits well with the rest of my terminal apps.

**Comment by alecthomas** [comment]
Have you tried to write your own style that works, or is this a limitation in the way Chroma interprets the styles?

**Comment by alecthomas** [comment]
Looks like something in Chroma:
![image](https://user-images.githubusercontent.com/41767/107104429-b6aa2b80-6875-11eb-8b9c-37c28fd04755.png)

**Comment by alecthomas** [comment]
So I don't think this is an issue with Chroma, it's just the way it is. If you want a theme that works out of the box on both light and dark, use `pygments`:
![image](https://user-images.githubusercontent.com/41767/107110792-e1f54080-689e-11eb-94bb-a9d9396ac68e.png)

**Comment by andyfeller** [comment]
> I wonder if there's been a misunderstanding here. I think what the OP was referring to is along the lines of this: https://jeffkreeftmeijer.com/vim-16-color:
> 
> > limiting [an app's] color scheme to 16 ANSI colors allows setting all color preferences in the terminal’s theme. Doing so results in consistent colors among terminal utilities and a color theme that’s quick to swap out for another one.
> 
> and
> 
> > By keeping the intent separate from the styling and the specific color values in the terminal theme, every utility in the terminal uses consistent colors. This makes changing themes—like switching between dark and light versions of a theme—a matter of pressing [a button] and selecting another one, without having to find a matching color scheme for [other apps].
> 
> So if chroma would have a theme that just uses the 16 ANSI colors that the terminal theme uses, that would allow users to not have to set chroma's theme separately (or rather only set it once, and then subsequently only change their terminal theme). So both the normal and the bright variant of these colors are what you want:
> 
> * black
> * red
> * green
> * yellow
> * blue
> * magenta
> * cyan
> * white
> 
> This is what I do with other CLI apps, as most of them have an ansi theme that adapts to the terminal theme. However, I don't think chroma does. And that's a shame, because there are a lot of nice cli apps out there that use chroma and therefore don't adapt to the term's color scheme. I think this should be reopened.

I think this is where an integrator would leverage the `terminal16` formatter to downsample the style to base 16 colors:

https://github.com/alecthomas/chroma/blob/4b0882a15f49a23c272b79b5af541bf918b98998/formatters/tty_indexed.go#L274-L279

**Comment by CarlQLange** [comment]
Hey, I've forked chroma and added this feature, so you can [reference `term-N` in a theme](https://github.com/CarlQLange/chroma/commit/e17dc5bd8beda17d3a0a92ce0a28c3b0ab76a225#diff-bf46528b3b52d2d56694bbbf69d15cb45877942144694be9f176cba940084087) and it'll emit the standard escape codes when rendered in a term and otherwise fallback. Doing it like this means that the displayed colour adapts when the terminal colours change (eg going from light to dark mode). It works on my machine and all the tests pass. To me, the code looks medium-to-good, but it was entirely vibe coded so I won't open a PR unless you're interested @alecthomas.

(My reasoning for this is that [glow](https://github.com/charmbracelet/glow) uses chroma, and glow supports this for its own theming but chroma does not, so code blocks would look bad if I switched terminal theme)

**Comment by alecthomas** [comment]
@CarlQLange did you try what @andyfeller suggested?

**Comment by CarlQLange** [comment]
@alecthomas No, it wasn't my preferred solution because that doesn't actually solve the problem I had, which is that I change my terminal colours when I switch from light to dark. Downsampling an existing theme colour to the nearest ANSI colour index still results in a fixed mapping that doesn't adapt when the terminal colours change. That solution doesn't solve the problem of "I've switched my terminal theme, but chroma still outputs a different theme" which this solution solves (and is also what the original poster and the ghost account were asking for). I didn't want to map from an existing chroma theme (which is Andy's suggestion), I wanted to directly set which ansi colour ids to use in a theme instead. Different problem, different solution.

<small>edit: Renamed the theme file in my fork to make it clearer that it works for any term theme, not just if your term is configured for modus</small>
