### ISSUE TITLE
Default `line` CSS `display: flex;` creating a problem if we want to inline a code snippet

### ISSUE THREAD

**Issue by kaushalmodi** [alecthomas/chroma#617]
In Hugo, we are working on a way to render **inline** code blocks.. i.e. just span/code tags and no pre tags.

The issue reported here stems from a change in https://github.com/alecthomas/chroma/pull/571 (/cc @CIAvash ) -- that the `line` class has `display: flex;` style set by default. If we are using classes for styling, we can override this. But we are using inline styles, we have to use a hack or a shortcode to remove that `display: flex;` style.

## Steps to reproduce the issue

Create a `t.el` with this content

```emacs-lisp
(message
"hello")
```

The aim is to render that code block **inline** i.e. new newlines. Above code snippet mimicks a real use case where an inline code snippet in Hugo blog post could line-wrap.

### Showing the issue

Replacing `pre` with `span` kind of does what I intend:

```
chroma --html --html-inline-styles t.el | sed 's/pre/span/g' > ! t.html  
```

This is the HTML:

```html
<html>
<body style="color:#e5e5e5;background-color:#000">
<span tabindex="0" style="color:#e5e5e5;background-color:#000;"><code><span style="display:flex;"><span>(message
</span></span><span style="display:flex;"><span><span style="color:#0ff;font-weight:bold">&#34;hello&#34;</span>)
</span></span></code></span>
</body>
</html>
```

This is how it renders:

![image](https://user-images.githubusercontent.com/3578197/157479090-3d25ed56-15c1-440d-9ebf-a213f13c19e8.png)

Note that the `display: flex;` is not truly making the rendering inline.

### Removal of `display:flex` fixes the issue

```
chroma --html --html-inline-styles t.el | sed 's/pre/span/g' | sed 's/flex/inline/g' > ! t.html   
```

This is the HTML now:

```html
<html>
<body style="color:#e5e5e5;background-color:#000">
<span tabindex="0" style="color:#e5e5e5;background-color:#000;"><code><span style="display:inline;"><span>(message
</span></span><span style="display:inline;"><span><span style="color:#0ff;font-weight:bold">&#34;hello&#34;</span>)
</span></span></code></span>
</body>
</html>
```

**Now** it renders as expected:

![image](https://user-images.githubusercontent.com/3578197/157479483-e26b05a0-bb4a-4b63-a711-38656ddc367a.png)

## Suggestion

Can the `display: flex;` style for `.chroma .line` be removed? I was able to get regular code blocks render well even without that CSS rule.

---

## Issue on Hugo

You can find the details of this issue will screenshots here: https://github.com/gohugoio/hugo/issues/9635#issuecomment-1062998742 but here is the gist.

If I try to add inline code in Hugo content using this:

```md
something {{< highlight emacs "hl_inline=true" >}}(message
"this highlight shortcode"){{</highlight>}} something
```

it gets rendered as below:

![image](https://user-images.githubusercontent.com/3578197/157462280-76c5615a-5442-43a5-83a3-c369e8f16e7f.png)

The `display: flex;` is causing the 2 lines in the code to float like that.

But using a Hugo shortcode, if I remove that `display: flex;` style, the rendering shows as expected:

![image](https://user-images.githubusercontent.com/3578197/157463274-01f0a204-c541-4ab6-be0e-dc06d037cbe2.png)

**Comment by CIAvash** [comment]
`display: flex;` was used to fix #558 (I don't remember if there were other reasons).

There is no need to replace `pre` manually there is an option for that, `PreventSurroundingPre`. There is also `WithPreWrapper` to supply your own wrapper.
```console
chroma --html --html-prevent-surrounding-pre --html-inline-styles
```

I understand that this is not what one wants in inline code, but IMO the current behavior is correct, there is two lines of code so you see two lines of code, otherwise all code lines will be shown as one line(unless it's wrapped in `pre`).
Use this command to see what I mean:
```console
chroma --html --html-prevent-surrounding-pre --html-inline-styles --html-lines t.el | sed 's/flex/inline/g' > /tmp/t.html
```

You should also be able to override the line style [like this](https://github.com/alecthomas/chroma/blob/7bfe2f41c6bbf6268ab06709b1361dc09f66b08a/cmd/chroma/main.go#L202), using `chroma.Line` class.

Another option is providing your own `PreWrapper` which contains a `code` tag with this style:
```css
code > span[style^="display:flex;"] {
   display: inline !important;
}
```

Or maybe there should be an option in Chroma to set if the code is inline or not.

I don't know how Hugo uses Chroma, so I can't suggest a perfect solution.

**Comment by kaushalmodi** [comment]
> chroma --html --html-prevent-surrounding-pre --html-inline-styles --html-lines t.el | sed 's/flex/inline/g' > /tmp/t.html

I understand that. But when I am inlining the code, 

- I cannot use `<pre>`
- Using line numbers doesn't make sense.

Here's a real world example of how I am using chroma highlighted inline code blocks on my Hugo generated blog:

![image](https://user-images.githubusercontent.com/3578197/157538368-31060fa4-24f0-45fa-b4fa-adeaab71e93c.png)

---

And if you do want the lines each on their separate lines, then retain the pre block. If you run below, you see that the code block renders just fine without any special `display` property styling.

```
chroma --html --html-inline-styles --html-lines t.el | sed 's/display:flex;//g' > ! t.html
```

---

## Summary

| Use case | Chroma options |
|-- |-- |
| Code block without tables, with line numbers | `--html-lines`, retains pre block by default, no need to customize `display` property |
| Inline code block (no line numbers) | `--html-prevent-surrounding-pre`, no need to  customize `display` property |

**Comment by kaushalmodi** [comment]
@CIAvash 

> display: flex; was used to fix https://github.com/alecthomas/chroma/issues/558

I read through the issue, but the issue creater was happy with `pre: grid;` solution. 

> I'm pretty happy with the first solution you suggested. 

---

If there's no real reason to add `.chroma .line { display: flex; }`, can that please be reverted. The `line` class can still be exported. If user wants, they can set `display: flex;` in their custom CSS.

**Comment by CIAvash** [comment]
My mistake, the fix for #558 is [this](https://github.com/alecthomas/chroma/blob/7bfe2f41c6bbf6268ab06709b1361dc09f66b08a/formatters/html/html.go#L445-L448).

The `display: flex` was used instead of `div` tag and `display: block` style(which is necessary for highlighting code). Maybe I did this to make #558 work even if there is no `PreWrapper`. I'm thinking if the `PreventSurroundingPre` is provided, then it means the code should be shown in one line.  So `display: block` should be added to `.line` only if there is a `PreWrapper` or do not add the line class when there is no wrapper.

I'll play with it a bit and see what I can do.

**Comment by alecthomas** [comment]
Thanks @CIAvash, I appreciate it.

**Comment by bep** [comment]
I see this code:

```go
classes[chroma.Line] = `display: flex;` + classes[chroma.Line]
```

I imagined I could override the display property with:

```go
builder.Add(chroma.Line, "display:inline;")
```

But (and with variations of the above) then I get:

```bash
invalid entry for Line: unknown style element "display:inline;"`
```

**Comment by CIAvash** [comment]
@bep hmm, that seems to be only for Pygments style entries. e.g. `bg:#F00`

**Comment by bep** [comment]
I see this discussion has spinned out into a new "InlineCode option", but I suggest to take that as a separate issue. This thread is about the `display: flex;` styling which it's not currently possible to override without some string replacement hacks, and that sounds like a bug that needs to be fixed first.

See my comment in https://github.com/alecthomas/chroma/issues/617#issuecomment-1063822264

**Comment by CIAvash** [comment]
From the original issue, that doesn't seem to be the goal of this "thread". They were looking for a way to fix the inline code issue.

But if the issue is overriding styles, I think either a new issue should be opened for it or the topic and content of this issue should be changed.

From my understanding the design follows Pygments' and this is how it's designed. @alecthomas can clarify if I'm wrong.

I see two solutions, writing your own html formatter or adding another option to html formatter. The option could look like this:
```go
func WithCustomStyles(styles map[TokenType]string) Option { 
        return func(f *Formatter) {
                f.customStyles = styles
        }
}
```

And then use the custom styles instead of the default ones if this option is provided.
