### ISSUE TITLE
No theme background color in TTY formatters

### ISSUE THREAD

**Issue by walles** [alecthomas/chroma#867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Background color is cleared in the TTY formatters.

Here's the code:
https://github.com/alecthomas/chroma/blob/2fa6f14bd6e7712bbea181fc4fcf71ee4b21163a/formatters/tty_truecolour.go#L13-L14

Here's the change where this was introduced:
73d11b3c4537e7a19ece1a702545a57f2f8c4393

But in my case I *want* the background color, as well as the foreground color.

How can I get that? Why is the background color stripped out?

### To Reproduce

See description.

**Comment by alecthomas** [comment]
The background colour is stripped out because it only sets the background of text, not the entire background of the terminal, so you end up with "bars" of background colour where the text is, and nothing in the rest of the terminal.

Your best bet is to copy the existing code and customise it to your requirements.

**Comment by walles** [comment]
Thanks for the clarification @alecthomas!
