### ISSUE TITLE
Evergarden missing in compat.go

### ISSUE THREAD

**Issue by rtfmkiesel** [alecthomas/chroma#980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `evergarden` style added in #970 is still missing from [compat.go](https://github.com/alecthomas/chroma/blob/master/styles/compat.go). 

### To Reproduce

Running `hugo gen chromastyles --style=evergarden` results in the wrong style even with the `chroma` module updated manually to the newest version.

**Comment by alecthomas** [comment]
As the bug template states, _please don't file bugs with reproduction steps for other projects_. If you can reproduce this in Chroma, then feel free to refile this bug. Additionall, as `compat.go` mentions, it is legacy and not being updated. But it also wouldn't have any bearing on whether a style is registered or not. As for whether the style shows up or not, it does in Chroma:

```
🐚 ~/dev/chroma $ chroma --list | grep evergarden                                                                                                                                                                                            master
styles: abap algol algol_nu arduino autumn average base16-snazzy borland bw catppuccin-frappe catppuccin-latte catppuccin-macchiato catppuccin-mocha colorful doom-one doom-one2 dracula emacs evergarden friendly fruity github github-dark gruvbox gruvbox-light hr_high_contrast hrdark igor lovelace manni modus-operandi modus-vivendi monokai monokailight murphy native nord nordic onedark onesenterprise paraiso-dark paraiso-light pastie perldoc pygments rainbow_dash rose-pine rose-pine-dawn rose-pine-moon rrt solarized-dark solarized-dark256 solarized-light swapoff tango tokyonight-day tokyonight-moon tokyonight-night tokyonight-storm trac vim vs vulcan witchhazel xcode xcode-dark
```


PS. Hugo typically only uses tagged versions, and there hasn't been a Chroma release since that style was added.
